/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.deathvader.guardian_bot;

import com.jagrosh.jdautilities.commons.waiter.EventWaiter;
import io.github.cdimascio.dotenv.Dotenv;
import me.duncte123.botcommons.web.WebUtils;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.hooks.AnnotatedEventManager;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

import javax.security.auth.login.LoginException;
import java.util.EnumSet;

public class Bot {
    public static Dotenv dotenv = Dotenv.load();
    public static JDA jda;
    public static String BOT_PREFIX = dotenv.get("BOT_PREFIX");
    EventWaiter eventWaiter = new EventWaiter();

    private Bot() throws LoginException {
        WebUtils.setUserAgent("Mozilla/5.0 ɢᴜᴀʀᴅɪᴀɴ#7105 / DΣΛƬΉVΛDΣЯ#0727");
        jda = JDABuilder.createDefault(dotenv.get("BOT_TOKEN"))
                .disableCache(EnumSet.of(CacheFlag.CLIENT_STATUS, CacheFlag.ACTIVITY))
                .enableCache(CacheFlag.VOICE_STATE, CacheFlag.EMOTE)
                .build();

        jda.setEventManager(new AnnotatedEventManager()); // Set event Manager Here
        WebUtils.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36");

        jda.getGatewayIntents().add(GatewayIntent.GUILD_MEMBERS);
        jda.getGatewayIntents().add(GatewayIntent.GUILD_MESSAGES);
        jda.getGatewayIntents().add(GatewayIntent.GUILD_MESSAGE_REACTIONS);
        jda.getGatewayIntents().add(GatewayIntent.GUILD_VOICE_STATES);
        jda.getGatewayIntents().add(GatewayIntent.GUILD_EMOJIS);

        jda.addEventListener(new Listener(eventWaiter), eventWaiter);
        jda.getPresence().setActivity(Activity.listening("$help | Servers " + jda.getGuilds().size() + 1));
    }

    public static void main(String[] args) throws LoginException { new Bot(); }
}
